### ISSUE TITLE
Support latest dependency `http: 1.0.0`

### ISSUE THREAD

**Issue by zeshuaro** [Workiva/json_schema#167]
## Type

Feature Request

## Details

Unable to use `json_schema` with latest version of `http: 1.0.0`
https://pub.dev/packages/http

## Possible Solution

Update `pubspec.yaml` with `http: ^1.0.0` and address any breaking changes

## Steps to Reproduce

1. Define both `json_schema: ^5.1.1` and `http: ^1.0.0` as dependencies in `pubspec.yaml`
2. `dart pub get` would fail to resolve the dependencies

## Your Environment

Not relevant

> __FYI:__ @michaelcarter-wf

**Comment by zeshuaro** [comment]
@jpeiffer that's not a good idea because it's a major version upgrade from 0.x.x to 1.x.x and probably contain breaking changes. So it's better to update the minimum requirement to the latest major version.

**Comment by jpeiffer** [comment]
In this case, it's a Google maintained project and they tend to keep things 0 based until they are confident the API is stable.  The differences between `0.13.4` and `1.0.0` are minimal technically and really instead signify the fact that Google has decided the API is stable enough to be called 1.0.0.  So by having the range you can support older clients while they continue to upgrade, as well as allowing newer ones to use the latest / stable.

**Comment by zeshuaro** [comment]
1.0.0 of http requires minimum Dart 3.0 which is a breaking change. So setting the constraint from 0.x to 1.x won't work.

**Comment by jpeiffer** [comment]
I did exactly that a few weeks back on a fork: https://pub.dev/packages/json_schema2

I'll discontinue the fork once it's uplifted here.

**Comment by michaelcarter-wf** [comment]
https://github.com/Workiva/json_schema/pull/168 is merged which widens the range to include http 1.0.0.

@zeshuaro Reading the release notes it's clear there are no breaking changes, so I went ahead and widened the range as @jpeiffer suggested.
@jpeiffer I think you're good to discontinue that fork?
@JKRhb Thanks for starting up some discussion around this!
