### ISSUE TITLE
Properties that match additionalProperties are not counted as evaluated

### ISSUE THREAD

**Issue by davidmorgan** [Workiva/json_schema#190]
## Details

With this schema

```
{
  "type": "object",
  "additionalProperties": {
    "type": "object",
  },
  "unevaluatedProperties": false
}
```

I believe the following should be valid

```
{"anyKey": {}}
```

but currently it fails validation.

## Possible Solution

I think I have the fix, I'll send a PR :)

## Steps to Reproduce

See test on PR :)

**Comment by joecotton-wk** [comment]
Closing because this has already been fixed.
