### ISSUE TITLE
incompatible with flutter_localizations

### ISSUE THREAD

**Issue by fribeau** [Workiva/json_schema#63]
## Details

I am trying to work with both flutter_localizations and json_schema packages but when I run flutter pub get I end up with the following errors:

```
The current Dart SDK version is 2.7.0.

Because no versions of json_schema match >2.2.1 <3.0.0 and json_schema 2.2.1 depends on w_transport ^3.2.8, json_schema ^2.2.1 requires w_transport ^3.2.8.
And because no versions of w_transport match >3.2.8 <4.0.0, json_schema ^2.2.1 requires w_transport 3.2.8.
And because w_transport 3.2.8 depends on sockjs_client_wrapper ^1.0.5 and no versions of sockjs_client_wrapper match >1.0.14 <2.0.0, json_schema ^2.2.1 requires sockjs_client_wrapper >=1.0.5 <=1.0.14.
Because sockjs_client_wrapper 1.0.14 depends on w_common ^1.20.1 and sockjs_client_wrapper >=1.0.5 <1.0.14 depends on w_common ^1.9.0, sockjs_client_wrapper >=1.0.5 <=1.0.14 requires w_common ^1.9.0.
Thus, json_schema ^2.2.1 requires w_common ^1.9.0.
Because w_common >=1.15.0 depends on intl >=0.14.0 <0.16.0 and w_common >=0.2.0 <1.15.0 requires SDK version >=1.12.0 <2.0.0, w_common >=0.2.0 requires intl >=0.14.0 <0.16.0.
Thus, json_schema ^2.2.1 requires intl >=0.14.0 <0.16.0.
And because every version of flutter_localizations from sdk depends on intl 0.16.0, json_schema ^2.2.1 is incompatible with flutter_localizations from sdk.
So, because esiquizz depends on both flutter_localizations any from sdk and json_schema ^2.2.1, version solving failed.

```

## Steps to Reproduce
This is my `pubspec.yaml` file:
```
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_schema: ^2.2.1
```

## Your Environment
Flutter doctor:
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.8-pre.17, on Linux, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

• No issues found!
```

> __FYI:__ @michaelcarter-wf

**Comment by rhalff** [comment]
If you have this problem you could in the mean time force an override from your project's pubspec.yaml:

```
dependency_overrides:
  intl: ^0.17.0 # json_schema's (w_common) dependency forces < 0.17.0
```

I think it would be save to just increase the version in the `w_common` package though.

It could be that Workiva isn't using this package in the context of Flutter so there is less of an urge to update this.

**Comment by michaelcarter-wf** [comment]
@fribeau @rhalff sorry for the super long lag. I wonder if this is still an issue for you with json_schema 3.0.1?

**Comment by rhalff** [comment]
I'm using a modified version of 2.2.2 at the moment, which is a [fork of a fork](https://github.com/dartlib/json_schema/commits/master). 

I haven't tried 3.0.1, my main issue was the package did not work with flutter_localization, no null-safety and there was browser specific code in the package which I removed. Is the new version compatible with Flutter?

**Comment by michaelcarter-wf** [comment]
There is browser specific code, but you can choose not to import it. The main `import 'package:json_schema/json_schema.dart'` does not include the browser code. Additionally, if you're using `JsonSchema.createSchema` over `JsonSchema.createSchemaAsync` you won't ever need this code. It's for fetching remote schemas. AFAIK, this lib should be fully flutter compatible.

**Comment by michaelcarter-wf** [comment]
Adding null-safety is on my todo list!

**Comment by michaelcarter-wf** [comment]
Null safety is now merged! :)
