### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by Windol** [Workiva/json_schema#65]
I am waiting for the acceptance of a pull request that I made some time ago and until today it has not been evaluated.

In addition to all the issues reported that are already affecting the use of this project as a dependency on new projects.

So, should I fork and republish the package to continue its development?

**Comment by SAGARSURI** [comment]
Yes, even I have the same question. I think it's no longer maintained. Is there any alternative to this library? @Windol

**Comment by jpeiffer** [comment]
I've been using this project for a while, and have recently been bit by the aging dependencies.  So I forked it and plain to maintain it.  It's mostly API compatible.  The two major differences are that you no longer need to explicitly tell it Browser or VM because it uses conditional package loading for that and I removed the generation of the HTML from Schema, because I have no need for that and no interest in maintaining that portion.

https://pub.dev/packages/json_schema2

**Comment by lynxnathan** [comment]
@jpeiffer couldn't find your fork. Got a repo for it up by any chance?

**Comment by michaelcarter-wf** [comment]
👋  Hello all. Yes, this repo is still maintained. Apologies for the long response lag. Workiva uses dart a little differently than most flutter consumers, which restricts the speed at which we can upgrade dart versions to a degree. @jpeiffer I'd be interested in merging in as many of your updates as possible, and I'm planning to try to get new draft support in fairly soon, time permitting.

**Comment by michaelcarter-wf** [comment]
We're doing some dependency upgrades here: https://github.com/Workiva/json_schema/pull/84/files

**Comment by JKRhb** [comment]
It seems to me as if the project has become a bit dormant again :( (I ported the library to sound null safety in https://github.com/Workiva/json_schema/pull/143, but unfortunately the review is still pending :/) Is there maybe the possibility that people could support you with reviews, @michaelcarter-wf? It would be great if a new version could be released in the near future.

**Comment by JKRhb** [comment]
As `json_schema2` by @jpeiffer does not support Draft 7 yet, I am considering publishing a `json_schema3` with the changes from #143 to have a current version with sound null-safety. Once a new upstream version has been published, I would mark it as discontinued. Or is sound null-safety on your roadmap for the near future anyway, making this unnecessary, @michaelcarter-wf?
