### ISSUE TITLE
Update to sound null-safety

### ISSUE THREAD

**Issue by crcdng** [Workiva/json_schema#80]
The current version of the package is not null-safe. 

Please update. https://dart.dev/null-safety/migration-guide

> __FYI:__ @michaelcarter-wf

**Comment by qurm** [comment]
Yes +1 for this.  Nowadays are too far into null-safe to even try a package that is not.  Too bad - looks great otherwise!

**Comment by JKRhb** [comment]
I started working on this issue in #143 :) I hope to get it done in the next few days.

**Comment by JKRhb** [comment]
#143 is ready now :) I hope that it can be merged soon.
